import { Dimensions, StyleSheet } from "react-native";

const screenHeight = Dimensions.get("window").height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFE066",
    justifyContent: "center",
    alignItems: "center",
  },
  background: {
    marginTop: screenHeight * 0.1,
    width: "115%",
    height: undefined,
    aspectRatio: 3.5,
  },
  statusBar: {
    position: "absolute",
    top: 20,
    left: 20,
    right: 20,
    borderRadius: 24,
    paddingVertical: 8,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    zIndex: 20,
  },
  profileContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#00000055",
    paddingHorizontal: 10,
    height: 50,
    width: 190,
    paddingVertical: 6,
    borderRadius: 50,
  },
  profileImage: {
    width: 30,
    height: 30,
    backgroundColor: "#eee",
    borderRadius: 14,
    marginRight: 15,
  },
  profileText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
    textAlign: "center",
  },
  statsContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  statGroup: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 16,
  },
  iconCircle: {
    width: 40,
    height: 40,
    borderRadius: 100,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 2,
  },
  statBox: {
    backgroundColor: "#6D5F2C",
    paddingHorizontal: 10,
    height: 30,
    paddingVertical: 4,
    borderRadius: 20,
    marginLeft: -20,
    minWidth: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  statText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  centerWrapper: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 5,
  },
  playButton: {
    width: 200,
    height: 200,
    borderRadius: 100,
    backgroundColor: "#FF3B3B",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 10,
    borderColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 10,
  },
  playButtonPressed: {
    transform: [{ scale: 0.96 }],
    shadowOpacity: 0.1,
    elevation: 3,
  },
  fakeModal: {
    position: "absolute",
    top: 100,
    left: 20,
    right: 20,
    padding: 20,
    backgroundColor: "white",
    borderRadius: 12,
    zIndex: 99,
    elevation: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 99,
  },
  rankingModal: {
    position: "absolute",
    top: "15%",
    left: "10%",
    right: "10%",
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingVertical: 20,
    paddingHorizontal: 16,
    elevation: 20,
    zIndex: 99,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 5,
    maxHeight: "70%",
  },
  modalHeader: {
    flexDirection: "column", // ✅ 세로 정렬
    alignItems: "flex-start", // ✅ 왼쪽 정렬
    marginBottom: 12,
    width: "100%",
  },
  characterModal: {
    width: "70%",
    height: "55%",
    backgroundColor: "#fff",
    borderRadius: 20,
    paddingHorizontal: 16,
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 24, // 자식 요소 간 간격
  },
  charactermodalHeader: {
    marginBottom: 12,
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  characterRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    width: "100%",
    paddingHorizontal: 10,
    marginTop: 20,
  },
  characterOption: {
    alignItems: "center",
    position: "relative",
  },
  characterImage: {
    width: 100,
    height: 80,
    resizeMode: "contain",
    maeginbottom: 16,
  },
  checkCircle: {
    position: "absolute",
    bottom: -25,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    flex: 1,
  },
  charactermodalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    flex: 1,
    marginTop: 20,
  },
  headerTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  closeButton: {
    position: "absolute",
    right: 0,
    color: "#757575",
  },
  periodText: {
    fontSize: 12,
    color: "#555",
    textAlign: "left",
    alignSelf: "flex-start",
    marginTop: 4,
    marginLeft: 4, // ← 살짝 들여쓰기 느낌
    maxWidth: "100%", // ← 부모를 넘지 않게
  },

  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#FFDD00",
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderRadius: 6,
    marginBottom: 6,
  },
  headerCell: {
    flex: 1,
    fontWeight: "bold",
    textAlign: "center",
  },
  scrollView: {
    maxHeight: 300,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  rowCell: {
    flex: 1,
    textAlign: "center",
    fontSize: 14,
  },
});
